<?php

namespace SchoolNameFaker\Provider;

class SchoolFaker extends \Faker\Provider\Base
{
    protected static $schoolNames = [
        "Esc. Normal Acad. Pedag. Pablo Apostol Managua",
        "Centro Escolar Maaswaal",
        "Centro Escolar La Libertad",
        "Centro Escolar Publico Oscar Omar Tellez Sanchez",
        "Centro Esc. Republica De El Salvador (Laureles Nor",
        "Fundac. Apoyo A La Infancia Monse\U00d1or Lezcano",
        "Colegio Latinoamericano Del Ejercito De Nicaragua Comandante Hugo Rafael Chavez Frias",
        "Colegio Publico Rigoberto Cruz Arguello",
        "Centro Escolar Carlos Mejia Godoy",
        "Escuela Azul Y Blanco Lening",
        "Colegio Publico  Edgar Arbizu",
        "Centro Escolar Rep. De Canada",
        "Colegio Republica De Venezuela",
        "Centro Escolar Publico Martha Lorena Lopez",
        "Centro Escolar Ottakring",
        "Centro Escolar San Jacinto",
        "Instituto Nacional  Villa Libertad",
        "Escuela Normal Maria Mazarello",
        "Nacional  Isaias Fillippi",
        "Centro Escolar Diriangen",
        "Instituto Nacional 1\U00ba De Mayo",
        "Centro Escolar Laureles Sur",
        "Colegio Miguel Bonilla Obando",
        "Colegio Caminos",
        "Alfonso Cortez",
        "Centro Educativo Carlos Fonseca Amador",
        "Centro Escolar  Francisco Morazan",
        "Centro Escolar  Panamericano (Zulema Balto",
        "Centro Educativo Benjamin Zeledon",
        "Cemtro Escolar Tenderi",
        "Centro Escolar  14 De Septiembre",
        "Centro De Educacion San Fermin",
        "Centro Escolar Anexo Pablo Antonio Cuadra - Las Enramadas",
        "Centro Escolar  Modesto Armijo Lozano",
        "Centro Escolar  Jap\U00d3n",
        "Centro Escolar Abc",
        "Centro Escolar Camilo Zapata",
        "Centro Escolar Corazon De Jesus",
        "Centro Escolar Adrian Rojas Narvaez",
        "Centro Escolar 22 De Septiembre",
        "Centro Escolar Barrilete De Colores",
        "Centro Escolar Centro Americana",
        "Centro Escolar Comandante Hugo Rafael Chavez Fria",
        "Centro Escolar Felix Ruben Garcia Sarmiento",
        "Centro Escolar Hispanidad (Camilo Ortega)",
        "Centro Escolar Enmanuel Mongalo",
        "Centro Escolar Flor De Sacuanjoche",
        "Centro Escolar Fidel Coloma",
        "Centro Escolar Dejad Los Ni\U00d1os Venid A Mi",
        "Centro Escolar Jose Dolores Estrada",
        "Centro Escolar Hugo Rafael Chavez Fria",
        "Centro Escolar Flor De Pino",
        "Centro Escolar Pedro Davila",
        "Centro Escolar Las Palmeritas",
        "Centro Escolar Publico Jos\U00c9 De La Cruz Mena",
        "Centro Escolar Maria Del Socorro Ponce Ch.",
        "Centro Escolar Jos\U00c9 De La Cruz Mena",
        "Centro Escolar Josefa Toledo N\U00ba 2",
        "Centro Escolar Las Americas",
        "Centro Escolar Jose Ramon Suarez Amador",
        "Centro Escolar Publico Modesto Bejarano",
        "Centro Escolar Republica De Alemania",
        "Centro Escolar Republica De Canada",
        "Centro Escolar Principe Guillermo De Luxemburgo",
        "Centro Escolar Pablo Antonio Cuadra",
        "Centro Escolar Miguel Larreynaga",
        "Centro Escolar Nuestra Se\U00d1ora De La Paz",
        "Centro Escolar Publico Nueva Esperanza",
        "Centro Escolar Publico Santos Lopez",
        "Centro Escolar Ni\U00d1o Jesus",
        "Centro Escolar Mis Primeros Pasitos",
        "Centro Escolar Publico Solidaridad Por La Paz",
        "Centro Escolar Publico Bertha Diaz",
        "Centro Escolar San Luis - Km. 10 Nejapa Sur",
        "Centro Escolar Walter Garcia Baltodano",
        "Centro Escolar Roberto Vargas Batres",
        "Centro Escolar Republica De Panama",
        "Centro Escolar Republica De Italia",
        "Colegio 12 De Septiembre",
        "Centro Escolar Ruben Dario #2 (La Hoyada)",
        "Colegio Azul Y Blanco",
        "Centro Escolar Santa Teresita",
        "Centro Escolar Santa Elena",
        "Centro Preventivo De Habilitacion Laboral Josefo Toledo De Aguerri",
        "Centro Escolar Salomon Ibarra Mayorga",
        "Centro Escolar Salomon Ibarra Mayorga",
        "Colegio Republica De Cuba",
        "Colegio Camilo Zapata",
        "Centro Escolar Santa Clara",
        "Colegio Publico Del Poder Ciudadano Nueva Libia",
        "Colegio Publico Carlos Blass Hernandez",
        "Centro Escolar Sn Joaquin De Las Jaguitas",
        "Colegio Publico Filemon Rivera Quintero",
        "Colegio Republica De Colombia",
        "Colegio Publico Douglas Lopez Ni\U00d1o",
        "Colegio Clementina Cabezas",
        "Colegio Publico Tomas Borge Martinez",
        "Colegio Guardabarranco",
        "Colegio Publico Ruben Dario",
        "Colegio Del Poder Ciudadano Experimental Mexico",
        "Colegio Del Poder Ciudadano Espa\U00d1a",
        "Colegio Josefa Toledo De Aguerri",
        "Colegio Pedro Joaquin Chamorro",
        "Colegio General Jose De San Martin",
        "Colegio Solidaridad",
        "Colegio Publico Del Poder Ciudadano 1ro De Junio",
        "Colegio Publico Santa Rosa",
        "Colegio Nacional   Nicarao",
        "Colegio Luxemburgo",
        "Colegio Rene Schick",
        "Colegio Pablo Antonio Cuadra - Los Vanegas",
        "Colegio Naciones Unidas",
        "Colegio Publico  De Esquipulas ( Anexo).",
        "Enmanuel Mongalo Y Rubio",
        "El Pilar",
        "Escuela Jean Paul Jenie",
        "Del Poder Ciudadano El Japon",
        "Escuela Del Poder Ciudadano El G\U00dceg\U00dcense",
        "Escuela Hilario Sanchez",
        "Escuela Concepcion De Maria",
        "Fernando Gordillo Cervantes",
        "Escuela Ramal Los Ladinos",
        "Escuela Publica Quinta Nina",
        "Escuela Publica Las Torres",
        "Esc. Reinaldo Antonio Tefel V\U00c9lez",
        "Instituto Nacional  Gaspar Garcia Laviana",
        "Escuela Milagros Porta",
        "Escuela Santo Domingo",
        "Escuela San Antonio Sur",
        "Instituto Nacional Publico Maestro Gabriel",
        "Escuela Republica De Costa Rica",
        "Gabriela Mistral",
        "Instituto Publico Enrique Flores Guevara",
        "Instituto Nacional  Ramirez Goyena",
        "Las Brisas",
        "Jaime Torrez Bodet",
        "Escuela Republica De Nicaragua",
        "Jose Benito Juarez",
        "Instituto Nacional  Camilo Zapata",
        "Instituto Nacional  De Esquipulas",
        "Instituto Nacional Elvis Diaz Romero",
        "Instituto Nacional  Salvador Mendieta",
        "Instituto Nacional Jose Antonio Hooker",
        "Jos\U00c9 Dolores Estrada",
        "Instituto Nacional  Miguel De Cervantes Sa",
        "Instituto Publico Rigoberto Lopez Perez",
        "Instituto Nacional Publico Del Poder Ciudadano Hugo Chavez",
        "Las Piedrecitas",
        "Nueva Espa\U00d1a (Esc. Ernesto Corea T.)",
        "Mercedes Campo",
        "Milagro De Dios",
        "Miguel Larreynaga #1 (Anexo Al Cea El Japon)",
        "Pedro Joaquin Chamorro Cardenal",
        "Preescolar Byron Diaz",
        "Preescolar La Sonrisa De Los Ni\U00d1os",
        "Ruben Dario Heroes Y Martires  #3",
        "Preescolar Madre Teresa De Calcuta",
        "Rafaela Herrera  (Cesar A. Solis)",
        "Wisconsin",
        "San Isidro De Bolas",
        "San Ignacio De Loyola",
        "Brett Bentley Crawford",
        "Virgen De Guadalupe",
        "Centro Escolar Maria Mora",
        "Centro Escolar  San Sebastian",
        "Centro Escolar Elemental Hospitalet",
        "Centro Escolar 15 De Septiembre",
        "Centro Escolar Fidel Coloma",
        "Centro Escolar Jose Dolores Estrada",
        "Centro Escolar San Antonio",
        "Centro Escolar Pablo Neruda",
        "Colegio Paul Harris",
        "Centro Estudios Madro\U00d1o",
        "Centro Escolar Pablo Antonio Cuadra",
        "Colegio Publico Del Poder Ciudadano Bello Horizont",
        "Centro Escolar Republica De Argentina",
        "Colegio Publico Luis Alfonso Velasquez Flores",
        "Centro Escolar Reyna Sofia",
        "Instituto Nacional  Salomon I. Mayorga",
        "Gabriela Mistral (M.De Los  Ang. L.)",
        "Escuela Especial Melania Morales",
        "Escuela Chiquilistagua",
        "Pablo Vi",
        "Liceo Benito Pititto La Bella (Carlos Fonseca A.)",
        "Escuela Normal Central De Managua-Alesio Blandon",
        "Escuela Normal Evangelica Sabatina \"Monte Sion\"",
        "Centro Educativo Getsemani",
        "Centro Educativo Ebenezer",
        "Centro Educativo El Buen Pastor Del Nazareno",
        "Centro Cristiano El Jordan",
        "Centro Cristiano Monte Horeb",
        "Centro Educativo El Rabi",
        "Centro Educativo Ruben Dario",
        "Centro Escolar Alamo Del Progreso",
        "Centro Educativo Jesus Es Mi Pastor",
        "Centro Educativo Bella Sonrisa",
        "Centro Educativo Privado Preescolar Smart Kids",
        "Centro Educativo Jardin De La Alegria",
        "Centro Educativo Disney",
        "Centro Educativo Privado Nicarahuac",
        "Centro Educativo Villa Flor",
        "Centro Escolar Galilea",
        "Colegio Buenas Orientaciones",
        "Escuela San Ignacio De Loyola",
        "Nueva Jerusalen",
        "Cristiano Cuerpo De Cristo",
        "Centro Educativo Cristiano Fuente De Salvacion",
        "Colegio Padre Faustino Miguez",
        "Colegio Emanuel",
        "Pre Escolar Colegio Republica De Nicaragua",
        "Instituto Privado Azul De Nicaragua",
        "Colegio Cristiano Fuente De Vida",
        "Escuela Biling\U00dce America",
        "Colegio Brazos De Amor",
        "Preescolar Privado Angelito",
        "Centro Escolar Reverendo Juan Simon Videa M",
        "Colegio Pureza De Maria",
        "Centro Escolar San Francisco De Asis",
        "Una Cita Con Dios",
        "Mis Primeras Letras",
        "Centro Escolar Liceo Cultural Nicarag\U00dcense",
        "Monte Sinai",
        "Instituto Salomon De La Selva",
        "Centro Escolar El Estudiante",
        "Centro Escolar La Cosecha",
        "Liceo Hispanidad",
        "Nuestra Se\U00d1ora Del Ancora",
        "Colegio Concepcion De Maria",
        "Shalom Christian School",
        "Centro Escolar Padre Bruno Martinez",
        "Instituto Centroamericano",
        "Colegio El Buen Pastor",
        "Preescolar Hno. Tom Patterson",
        "Centro Escolar Mis Aventuras",
        "Centro Escolar San Jose",
        "Centro Escolar Raflang",
        "Escuela Mizpa",
        "Colegio El Sendero Divino",
        "Jardin Infantil Peque\U00d1ines",
        "Preescolar Castillo",
        "Colegio Bautista Hebron",
        "Colegio Cristiano Divino Maestro",
        "Centro Educativo San Jose Vencedor",
        "Centro Educativo Privado El Se\U00d1or Es Mi Pastor N\U00b02",
        "Centro Escolar Jesus El Buen Pastor",
        "Preescolar Dora Maria Urroz",
        "Colegio Hispano Americano",
        "Centro Escolar Piolin Y La Fe",
        "Educaci\U00d3n Temprana",
        "Centro Escolar Los Cari\U00d1ositos",
        "Colegio Altamar",
        "Centro Educativo Ni\U00d1o Jesus De Praga",
        "Bautista El Calvario",
        "Centro De Educacion Integral De Managua",
        "Centro Alternativo Escuela Taller-Adc",
        "Centro De Formacion Educativo Para Persona Ciegas",
        "Centro Educativo Xilonem",
        "Angelita Morales",
        "Centro Educativo  Abejita Hutch",
        "Preescolar Ni\U00d1o Jesus Fundador",
        "Adventista Roberto Eubanks",
        "American Study Center",
        "Academia Cristiana De Nicaragua",
        "Adventista Reparto Shick",
        "Centro Educativo Bilingue Alfa",
        "Antorcha Divina",
        "C.D.I Las Mercedes",
        "Centro Educativo Fares",
        "Centro De Atencion Infantil El Jardin De Peppa",
        "C.E Colegio Nicarguense Frances \"Victor Hugo\"",
        "Bambini Montessori",
        "Centro De Estudiosan Miguel Arcangel",
        "Centro Educativo Cristo Del Rosario",
        "Centro Educativo Cristiano \"El Se\U00d1or Es Mi Pastor\"",
        "Centro Educativo Privado Cristy",
        "Centro Educativo Privado Preescolar Ni\U00d1o Feliz",
        "Centro Educativo Guardabarranco",
        "Centro Educativo Rubenia",
        "Centro Escolar Agape La Chureca",
        "Centro Educativo Bambito",
        "Centro De Estudios Karen Jolley",
        "Centro Educativo Cristiano Pochocuape",
        "Centro Educativo Rayitos De Gloria",
        "Centro Educativo Bereshit",
        "Centro Educativo A\U00d1os Magicos",
        "Centro Educativo Rayito De Sol",
        "Centro Educativo Kales",
        "Centro Educativo Nicaraguense Los Angeles",
        "Centro Educativo Cristiano Jehova Sama",
        "Centro Educativo Nicaraguita",
        "Centro De Desarrollo Infantil \"Eduardo Contreras\"",
        "Centro Educativo Capa Y Capi",
        "Centro Educativo Macedonia",
        "Centro Educativo El Alba",
        "Centro Educativo Einstein Academy",
        "Centro Escolar \"Divino Salvador\"",
        "Centro Educativo Privado Cristiano Montecristi",
        "Centro Educativo Privado Pekes Garden",
        "Centro Educativo Ni\U00d1os Con Esperanza",
        "Centro Educativo Pastorsitos De Fatima",
        "Centro Educativo Conocimiento",
        "Cemtr Escolar Educativo Jerusalen",
        "Centro Escolar Chavalitos",
        "Centro Escolar La Esperanza",
        "Centro Escolar Inst. De Educ. Intermedia Juan Baut",
        "Centro Escolar Inst. Privado \"La Purisima\"",
        "Centro Escolar El Peque\U00d1o Jes\U00das",
        "Centro Escolar El Camino",
        "Centro Escolar Maria De Fatima",
        "Academia De Santa Maria",
        "Centro Escolar El Mesias",
        "Centro Escolar Academiia Crisitiana De Managua",
        "Centro Escolar Capacitacion Comercial",
        "Centro Escolar Parroquial \"San Pio X\"",
        "Centro Escolar Mis Primeros Ilusiones",
        "Centro Escolar Jardin Infantil Divino Ni\U00d1o",
        "Centro Escolar Kinder Misha",
        "Centro Escolar Primera Iglesia De Cristo",
        "Centro Escolar Cristiano Genesis",
        "Centro Escolar Jesus El Maestro",
        "Centro Escolar La Purisima De Torrez Molina",
        "Centro Escolar Mis Primeros Conocimientos",
        "Centro Escolar Hermanos Dunklee",
        "Centro Escolar Los Pollitos",
        "Centro Escolar Fuente De Sabiduria",
        "Ananda Marga",
        "Centro Escolar Cristo Viene.",
        "Centro Escolar Enrique De Osso",
        "Centro Escolar Israel",
        "Colegio Adventista Metropolitano",
        "Centro Escolar Sacuanjoche",
        "Colegio Cristiano Nueva Jerusalen",
        "Colegio Bautista",
        "Colegio Cristiano Centro_Evangel\U00cdstico",
        "Escuelita Privada De Preescolar Constructores Del Futuro",
        "Centro Escolar San Sebastian",
        "Centro Escolar Sagrado Corazon De Jesus",
        "Colegio Cristiano Gamaliel",
        "Colegio Jesus Divino Obrero",
        "Colegio Cristo Rey",
        "Colegio Cristiano El Mesias",
        "Colegio Bautista Belen",
        "Centro Escolar Santa Clara De Asis",
        "Centro Escolar Primer Templo Biblico",
        "Colegio Santa Luisa De Marillac",
        "Colegio Cristiano Herm\U00d3n",
        "Centro Escolar Parroquial Belen",
        "Centro Escolar Unidos En Cristo",
        "Centro Escolar Triana",
        "Colegio De La Anunciacion",
        "Colegio Cristiano Tabernaculo Agua Viva",
        "Colegio Angloamericano",
        "Colegio Bautista Horeb",
        "Colegio Centro  America",
        "Centro Escolar Trinity Christian School",
        "Colegio Cristiano Presbiteriano De Nicaragua",
        "Centroam\U00c9rica Unida",
        "Colegio Adventista Reparto Schick",
        "Colegio Bautista Canaan",
        "Colegio Cristiano La Verde Sonrisa",
        "Colegio Mont Berkeley",
        "Colegio Americano Nicaraguense",
        "Colegio Alfonsin",
        "Cristiano Nicaraguense",
        "Centro Escolar St.Augustine Preparatory School",
        "Centro Infantil Nuevas Experiencias",
        "Colegio Calasanz",
        "Colegio Central De Nicaragua",
        "Colegio Cristiano Restauracion",
        "Colegio Regina Mater",
        "Doris Maria Morales",
        "Centro.Educativo Divino Ni\U00d1o (Wilfredo Valenzuela)",
        "Colegio Cristiano Huerto De Dios",
        "Centro Escolar Sor Maria Romero",
        "Colegio Bautista Las Brisas",
        "Centro Infantil El Camino",
        "Colegio Cristiano Jehova Reina",
        "Colegio Nicaraguense El Buen Pastor",
        "Colegio Cristiano Bethel Milagro De Dios",
        "Colegio Tabern\U00c1culo Evang\U00c9lico",
        "Colegio Soldado De La Cruz",
        "Colegio Bautista El Redentor",
        "Colegio Parroquial Sagrada Familia No. 2",
        "Colegio Agustiniano",
        "Centro Escolar Zacarias Guerra",
        "Colegio Azul De Nicaragua",
        "Dios Es Amor",
        "Escuela Bautista Genezareth \"Los Pajaritos\"",
        "Colegio Flor De Loto",
        "Escuela Parroquial Santa Ana",
        "Escuela Bautista Monte Horeb",
        "Einstein Academy",
        "El Shaddai",
        "Escuela Casa Nazareth",
        "Escuela Inmaculada  Coraz\U00d3n De Mar\U00cda",
        "Colegio Vocacional Adventista De Nicaragua",
        "Escorar Monte Sinai",
        "Colegio Evangelico Amigo \"Berea\"",
        "Colegio Hermosa Rosa De Saron",
        "Escuela Cristiana Oasis De Esperanza",
        "Colegio Cristiano El Faro",
        "Colegio Cristino Monte De Sion",
        "Escuela Universal Pierre Y Marie Curie",
        "Colegio Madre Del Verbo",
        "Colegio Girasol",
        "Colegio Tecnologico Central",
        "Colegio El Buen Pastor Metodista Libre",
        "Colegio Teresiano",
        "Colegio S.O.S Herman Gmeiner",
        "El Rey Salom\U00d3n",
        "Escuela Centroamericana De Comercio",
        "Divino Conocimiento",
        "Colegio Pan Y Amor San Jose",
        "Escuela Cristo Obrero",
        "Colegio Cristiano El Padul",
        "Colegio Privado Valley Internacional School",
        "Escuela De Computacion Y Comercio Silviano Matamor",
        "Escuela Parroquial Maria Inmaculada",
        "Escuela Madre Cayetana Alberta",
        "Fe Y Esperanza",
        "Instituto Tecnico Jose Dolores Estrada",
        "Escuela Cristiana Carolina De Sirker",
        "Instituto Del Valle",
        "Escuela Parroquial Hermano Pedro Betanc",
        "Escuela Jos\U00c9 Maria Vilaseca",
        "Jardin Infantil La Ardillita",
        "Internacional College",
        "Instituto Catolico Juan Pablo Ii",
        "Escuela Cristiana Isaias 29:18",
        "Kinder Los Angeles",
        "Instituto De Computacion Y Comercio Independencia 2",
        "Jardin Infantil Caritas Alegres",
        "Escuela Cristiana Emilia De Sirker",
        "Escuela San Martin De Porres",
        "Escuela San Jose De La Ca\U00d1ada",
        "Escuela Parroquia Monte Tabor",
        "Escuela Parroquial Santa Faz",
        "Instituto Tecnico La Inmaculada",
        "Escuela Parroquial San Judas Tadeo",
        "Instituto Independencia",
        "Escuela Parroquial Monse\U00d1or Oswaldo Mondrag\U00d3n",
        "Instituto De Secundaria Ilcomp",
        "Lumen Christi",
        "Instituto Pedagogico Arcoiris",
        "Madre Del Divino Pastor",
        "Kinder Sagrada Familia",
        "Instituto Loyola",
        "Jardin Infantil Gasparin",
        "Hands On Innovative Learning",
        "Kinder Wonder Age",
        "Instituto Pedagogico La Salle",
        "Kids Academy",
        "Kinder Montessori, Lideres Del Futuro",
        "Instituto Privado Domingo Savio (Padre Fabretto)",
        "Kinder Rinconcito De Guadalupe",
        "Instituto Tecnologico Monse\U00d1or Nicolas A.Madrigal",
        "Kinder Jardin De Maria",
        "Liceo Privado \"Bello Horizonte\"",
        "Liceo Fidel Coloma",
        "John F. Kennedy High School",
        "Nicaragua Cristian Academy - Nejapa",
        "Liceo Cristiano Bethesda",
        "Jardin De Infantes Pinocho",
        "Kinder Cristy",
        "Preescolar Bertha",
        "Kinder Home Sweet Home",
        "Jardin Infantil Campanita",
        "Liceo Franciscano",
        "Margarita Tuite",
        "Parroquia Cristo Resucitado",
        "Kinder Santa Clara",
        "Kinder Montessori",
        "Jardin Infantil Campanitas De Abril",
        "Jardin Infantil Carrusel Es Alegria",
        "Lincoln International Academy",
        "Preescolar Arco Iris",
        "Pre Escolar Las Ardillitas",
        "Jardin Infantil Coro De Angeles",
        "Instituto Central Nicaraguense Icn",
        "Preescolar Globitos",
        "Preescolar Sagrada Familia",
        "Preescolar Arcoiris",
        "Preescolar Almedrita",
        "Preescolar My Little Sleps Abc",
        "Rayito De Sol",
        "Nuevo Amanecer",
        "Preescolar Belamar",
        "Preescolar Chiquischool",
        "Preescolar Massiel Y Lamar",
        "Liceo Privado Milagro De Dios",
        "Preescolar My House Montessori",
        "Preescolar Abc Educacion Integral",
        "Preescolar El Trencito Del Saber",
        "Preescolar Los Angelitos",
        "Rayito De Luz",
        "Preescolar El Jardin De Manzanita",
        "Monse\U00d1or Lezcano La Salle",
        "Nuestra Se\U00d1ora De Fatima",
        "Mi Redentor",
        "Ms.Claudias Daycare Preschool",
        "Preescolar Bilingue Eco English",
        "Preescolar \"Candy\"",
        "Mundo Montessori Comunidad Infantil",
        "Preescolar Kiddie Stop Villa Fontana",
        "Preescolar Kinder Montessori",
        "Preescolar San Martin",
        "Preesc. Jardin Infantil Cristiano \"Las Praderitas\"",
        "Pre Escolar Saint Martin",
        "Preescolar Guarderia Universo De Los Ni\U00d1os",
        "Preescolar Academia Cristiana Las Torres",
        "Preescolar Kids Y Babies",
        "Reverendo Boanerge Aragon Noli",
        "San Francisco De Asis",
        "Santa Gema",
        "Preescolar Privado Kiddie College",
        "Preescolar Amiguitos",
        "Preescolar John F. Cordisco",
        "Prescolar Centro Educacion Hijo Del Rey",
        "Preescolar Fourier Children`S Garden",
        "Preparatoria-Unicas",
        "Preescolar Cristiano Waterview",
        "Preescolar Esmirna",
        "Sagrada Familia #1",
        "Preescolar Proyecto Educativo El Eden",
        "Saint Dominic School",
        "Savanna International School",
        "Preescolar Privado Las Abejitas",
        "Preescolar Kinder Ker",
        "Preescolar Kiddie Stop Bolonia",
        "Santa Clara",
        "Sagrada Familia De Nazaret",
        "Verbo Divino",
        "Preescolar Julia Herrera De Pomares",
        "The Learning Tree",
        "Preescolar Privado Ivania - Divina Misericordia",
        "Preescolar Jean Piaget",
        "Rev. Marcelino Davila Castillo",
        "The Norte Dame School",
        "Capilla Del Calvario",
        "Preescolar San Francisco Asis 2",
        "School My First Steps",
        "Preescolar Estrellita",
        "Preescolar Mente Geniales",
        "Centro Escolar Madre Del Divino Pastor (Nejapa)",
        "Centro Escolar Nuestra Sra: Del Carmen",
        "Centro Escolar Santa Maria Reyna De Las Gracias",
        "Centro Escolar Aleman Nicarguense",
        "Centro Escolar Beerseba",
        "Centro Educativo Privado Planeta Verde",
        "Centro Escolar Nueva Nicaragua",
        "Centro Educativo El Rey Poderoso",
        "Centro Escolar Politecnica De Comercio",
        "Colegio Bilingue Maria Inmaculada Concepci\U00d3n",
        "El Nuevo Pacto Asamblea De Dios",
        "Colegio Cristiano La Senda",
        "Colegio Nordico Internacional",
        "Colegio San Agustin",
        "Centro Escolar Academia De Excelencia Hosana",
        "Ctro Social Sos Herman Gmeiner",
        "Hanzel Y Grethel",
        "Colegio Hispano Nicaraguense",
        "Colegio Centro De Fe Vida Nueva",
        "Escuela San Jose (Cent. Aten. Al N.)",
        "Centro Educativo G\U00c9nesis",
        "Colegio Parroquial San Rafael No. 1",
        "Centro Escolar Evangelico La Esperanza (Manantial Vida E.)",
        "Escuela Cristiana Arca De Noe",
        "Colegio Apostolico Leonardo Sepulveda",
        "Centro Escolar Monte Si\U00d3n",
        "Enmanuel Mongalo N\U00ba 1",
        "Centro Escolar Metodista Libre",
        "Colegio Pentecostal Rios De Agua Viva",
        "Colegio Cristiano Bethel",
        "Instituto De Secundaria Olimpia",
        "Preescolar Nihao",
        "Monte Herm\U00d3n.",
        "Preescolar Eko Kinder",
        "Preescolar Bilingue Pure Heart School",
        "Preescolar First Steps Daycare Center",
        "Jardin Infantil Melania Lopez",
        "Santo Domingo De Guzman",
        "Juan Xxiii Fe Y Alegria",
        "Jehova Jireh",
        "Solidaridad Entre Los Pueblos",
        "Jardin Infantil Ruben Dario",
        "Luz Del Saber",
        "Lighthouse Christan Academy",
        "Preescolar Peter Pan",
        "Preescolar Jardin Infantil Winnie Pooh",
        "Preescolar Bilingue Happy Face",
        "Instituto El Maestro",
        "School Of Higher Learning",
        "Instituto Cristiano Stilecrofft",
        "Instituto Bilingue Kingdom School",
        "Casa De Ni\U00d1os Montesorri",
        "Centro Educativo Cardenal Miguel Obando Y Bravo",
        "Centro Educativo Cristo Rey",
        "Centro Educativo Divino Ni\U00d1o",
        "Anexo Centro Escolar Catolico Juan Pablo Ii",
        "Centro Educativo Bilingue Nueva Nicaragua",
        "Centro Escolar Blanquita Ramirez",
        "Centro Escolar Adventista El Paraisito",
        "Centro Escolar El Buen Pastor # 2",
        "Centro Escolar Nuestra Se\U00d1ora De Guadalupe",
        "Centro Escolar Parroquial Reina De La Paz",
        "Centro Escolar Oscar Chavarria Duarte",
        "Colegio Del Sagrado Corazon De Jesus Bethlemitas",
        "Escuela Parroquial Asuncion De Maria",
        "Colegio Pureza De Maria",
        "Colegio Cristiano El Buen Pastor",
        "Ctro Educativo Ntra S\U00d1ra De La Caridad",
        "Instituto Tecnico Especializado Juan Pablo Ii",
        "Escuela Bautista Libertad",
        "Instituto Cristiano La Palabra",
        "Instituto Inmaculada Concepcion",
        "La Casita Azul Nuestra Se\U00d1ora Del Pilar",
        "Escuela Espa\U00d1ola Infancia Sin Fronteras N\U00ba2",
        "Kinder Rayito De Luz",
        "Preescolar Privado Cantar De Los Cantares",
        "Preescolar Mis Primeros Pasitos",
        "Preescolar Cenicienta",
        "Preescolar Bertha",
        "Preescolar Bilingue Iberoamericano Nicaraguense",
        "Centro Escolar Rodolfo Rodriguez Alvarado",
        "Centro Educativo Padre Luis Antonio Almendarez",
        "Esc. Cristiana Rev. Kennet R. Hanna",
        "El Limon",
        "El Cipres",
        "El Madro\U00d1o",
        "Admiracion Las Pe\U00d1itas",
        "La Trinidad",
        "Los Robles",
        "El Delirio",
        "Benedicto Bravo Urbina",
        "Arco Iris De Amor",
        "Centro Escolar  Horacio Aguilar Bucardo",
        "C.Escolar Violeta  Barrios De Chamorro",
        "Centro Escolar Amparo Astorga Solano",
        "Caupolican",
        "Buenos Aires",
        "Bello Amanecer",
        "Alfonso Cortez",
        "Centro Escolar 3 De Septiembre",
        "Centro Escolar Andres Castro",
        "Centro Escolar Carlos Mejia Godoy",
        "Centro Escolar Belen",
        "Centro Escolar  Miguel Obando M.",
        "Alfa Y Omega",
        "Centro Escolar Augusto C. Sandino",
        "Centro Escolar Buena Esperanza",
        "Centro Escolar Arca Del Saber",
        "Centro Escolar Cristo Rey No 2",
        "Centro Escolar El Alfarero",
        "Centro Escolar El Amanecer",
        "Centro Escolar Carlos Fonseca Amador",
        "Centro Escolar Elena Arellano",
        "Centro Escolar El Nazareno",
        "Centro Escolar El Corozo",
        "Centro Escolar El Canada",
        "Centro Escolar Edelberto Torrez",
        "Centro Escolar Enmanuel Mongalo",
        "Centro Escolar Gabriel Morales",
        "Centro Escolar Fco. Hernandez De Cordobas",
        "Centro Escolar El Olivar",
        "Centro Escolar Estado Quebec",
        "Centro Escolar Henry Dunant",
        "Centro Escolar Hnos En Cristo",
        "Centro Escolar Josefa Toledo De Aguerri",
        "Centro Escolar Ivan Sequeira Cerrato",
        "Centro Escolar Julio Cesar Ochoa",
        "Centro Escolar Juan Francisco Salinas",
        "Centro Escolar Heroes Y Martires",
        "Centro Escolar La Nueva Union",
        "Centro Escolar Los Dos Hermanos",
        "Centro Escolar Loma Linda",
        "Centro Escolar Las Americas",
        "Centro Escolar Maria Auxiliadora No 2",
        "Centro Escolar Loma Linda N\U00ba2",
        "Centro Escolar Lydia Saavedra",
        "Centro Escolar Las Ma\U00d1anitas",
        "Centro Escolar Madre Guadalupe Caldera",
        "Centro Escolar Los Angeles",
        "Centro Escolar Miguel Larreynaga",
        "Centro Escolar Nue Luz N\U00ba2",
        "Centro Escolar Leonesl Rugama",
        "Centro Escolar Los Pastorsitos",
        "Centro Escolar Nueva Esperanza",
        "Centro Escolar Salmo 91",
        "Centro Escolar Rafael Benites",
        "Centro Escolar Nuevo Amanecer",
        "Centro Escolar Republica De Holanda",
        "Centro Escolar Rafaela Herrera No. 2",
        "Centro Escolar Sagrada Familia",
        "Centro Escolar Rosita",
        "Centro Escolar San Juan",
        "Centro Escolar San Rafael #2",
        "Centro Escolar San Agustin",
        "Centro Escolar San Isidro # 2",
        "Centro Escolar Samaria",
        "Centro Escolar San Pablo No. 4",
        "Centro Escolar Ruben Dario Numero 2",
        "Centro Escolar Santa Rosa #2",
        "Centro Escolar San Ramon",
        "Centro Escolar Santa Rosa",
        "Centrs Escolar 14 De Septiembre",
        "Cristo Redentor",
        "El Castillo # 2",
        "Divino Ni\U00d1o",
        "Divino Pastor N\U00b02",
        "El Diamante No.1",
        "El Jasm\U00cdn",
        "El Naranjo",
        "El Guardabarranco",
        "Cristobal Colon",
        "El Esfuerzo",
        "Cristo Rey",
        "Cristo Rey",
        "El Virgen",
        "Escuela El Consuelo",
        "Eduardo Jiron Valle",
        "El Cisne",
        "Escuela   Alfa #2",
        "El Rosario",
        "El Carmen",
        "El Paraiso",
        "El Paraiso #2",
        "Escuela La Fraternidad",
        "El Progreso #2",
        "El Volcan",
        "El Madro\U00d1o",
        "El Oto\U00d1o",
        "Divino Pastor No. 3",
        "El Jardin De San Jose",
        "Gabriela Mistral",
        "Hermanos En Cristo #2 (Pipitos)",
        "Escuela La Sabiduria",
        "Emaus",
        "Escuela San Jose",
        "El Jovito",
        "Instituto Nacional Berardo De Cirauqui",
        "Escuela Rayo De Sol",
        "Escuela Fe Y Esperanza",
        "La Concepcion",
        "Jose Dolores Estradas",
        "Flor De Pino # 2",
        "Juan Xxiii",
        "La Posolita",
        "Jehova Es Mi Pastor",
        "La Primavera",
        "Escuela San Juan Bautista",
        "La Union",
        "Las Mercedes",
        "La Esperanza",
        "La Sorpresa",
        "La Felicidad",
        "Monte De Los Olivos",
        "Jos\U00c9 Mart\U00cd",
        "Los Cocos",
        "Mis Deseos",
        "Los Pajaritos",
        "Mons. Salvador",
        "Las Margaritas",
        "Nuestra Se\U00d1ora De Guadalupe",
        "Maria Montessori",
        "Ni\U00d1a Bonita",
        "Pablo Antonio Cuadra",
        "Nueva Luz",
        "Nuevo Renacer",
        "La Florida",
        "Nuestra Se\U00d1ora Del Socorro",
        "Monte Oreth",
        "Los Olivos N.2",
        "Los Laureles",
        "Centro Escolar Loma Linda",
        "Patria",
        "San Benito N\U00ba 1",
        "Nicaraguita",
        "Nueva Alegria",
        "Pedro Joaquin Chamorro",
        "San Cristobal",
        "Pueblo Nuevo",
        "San Luis",
        "Preescolar Villa Austria",
        "San Antonio",
        "San Jorge",
        "San Jose",
        "Preescolar Hugo Chavez",
        "San Pablo #2",
        "San Bernardo",
        "Sagrado Corazon De Jesus",
        "Rafaela Herrera",
        "Salomon Ibarra",
        "San Francisco",
        "Santa Luz",
        "Santa Esther",
        "San Jose (Chalmeca Arriba)",
        "San Jeronimo",
        "Santa Fe N\U00b02",
        "Sant\U00cdsima Trinidad",
        "San Mateo",
        "Violeta Barrios De Chamorro",
        "Santa Fe",
        "Santa Rita",
        "Centro Escolar Antonio Mejia",
        "Centro Escolar Diriangen",
        "Centro Escolar El Buen Samaritano",
        "Centro Escolar Nicarao",
        "Centro Escolar La Buena Esperanza",
        "Centro Escolar Los Laureles #2",
        "Centro Escolar San Francisco De Asis # 2",
        "Filadelfia",
        "Genesis",
        "Escolar Corazon De Jesus",
        "La De Buena Esperanza",
        "Guadalupe",
        "Ruben Dario # 2",
        "La Virgen",
        "La Estrellita",
        "Reberendo German Garcia",
        "Perpetuo Del Socorro",
        "Preescolar Rafael Rosales",
        "Santa Isabel (Sisi)",
        "San Miguel",
        "Sendero De Vida",
        "Sn Agustin",
        "Escuela San Damian",
        "Centro Escolar Gracias A Dios",
        "Centro Escolar Bautista Bethel",
        "Centro Escolar El Papelito",
        "Corazon De Maria",
        "Centro Escolar San Antonio (San Jose No 4)",
        "Centro Escolar Santo Tomas",
        "Centro Escolar Ruben Dario",
        "Centro Escolar San Francisco De Asis",
        "Centro Escolar San Martin",
        "Centro Escolar Santa Rita No 2",
        "Escuela La Santa Clara",
        "Escuela Jardin Del Eden",
        "Escuela Manuel Estrada Carpintero",
        "Escuela San Miguel",
        "Escuela El Manzano",
        "Escuela San Patricio",
        "Escuela Divino Ni\U00d1o #2",
        "Escuela San Rafael No.2",
        "Escuela Jose Dolores Estrada",
        "Escuela San Nicolas",
        "Concepcion De Maria",
        "Miguel Larreynaga #2",
        "Los Angeles",
        "La Concepci\U00d3n #2",
        "La Salle",
        "Monte Rosa Sur",
        "Nuestra Se\U00d1ora De Fatima",
        "Jose Tous",
        "San Valentin",
        "San Isidro - R\U00cdo Plata",
        "San Antonio",
        "San Jose",
        "San Jose #2 (El Castillo)",
        "San Juan",
        "San Francisco- Minas De Kisilala",
        "San Rafael # 1",
        "Centro Escolar Nueva Luz",
        "Santa Fe",
        "El Efuerzo",
        "Nuevo Amanecer",
        "Corazon De Jesus",
        "Escuela La Trinidad",
        "Rafael Herrera # 3",
        "Centro Escolar Georgino Andrade",
        "Centro Escolar Maria Auxiliadora",
        "El Eden",
        "San Jose",
        "Cemtro Escolar Ricardo Morales Aviles",
        "Centro Escolar Bernardino Diaz Ochoa",
        "Escuela Mario P\U00c9rez",
        "Nuevo Amanecer",
        "Nicasio Nu\U00d1ez",
        "El Nazareno",
        "Centro Escolar El Milagro #3",
        "Centro Escolar El Pejibaye",
        "Centro Escolar La Esperanza",
        "Escuela La Vi\U00d1a",
        "Centro Escolar San Marcos",
        "Centro Escolar Linda Vista",
        "Bella Vista",
        "Andres Castro #2",
        "Centro Escolar Bello Amanecer",
        "Centro Escolar Benjamin Zeledon",
        "Arturo Jose Valdez Robleto",
        "Azarias H. Pallais",
        "Escuela Normal 8 De Octubre",
        "Virgen De Loreto",
        "Barcelona",
        "Bello Amanecer",
        "Buenos Aires",
        "Centro De Educacion Primaria La Union",
        "Centro Escolar Argentina",
        "El Naranjal",
        "Centro Escolar Carlos Fonseca",
        "Centro Escolar El Amanecer",
        "Centro Escolar Cristo Redentor",
        "Centro Escolar Bethel",
        "Centro Escolar El Triunfo",
        "Centro Escolar El Jardin",
        "Centro Escolar El Madro\U00d1o",
        "Centro Escolar El Progreso",
        "Centro Escolar El Papayo",
        "Centro Escolar El Progreso No.2",
        "Centro Escolar El Porvenir",
        "Centro Escolar El Alfarero",
        "Centro Escolar Divino Redentor",
        "Centro Escolar El Naranjo 1",
        "Centro Escolar Esperanza N\U00ba2",
        "Centro Escolar Hogar De Encanto",
        "Centro Escolar Escuela El Manantial",
        "Centro Escolar Fatima",
        "Centro Escolar Guardabarranco",
        "Centro Escolar Estrella De Belen",
        "Centro Escolar General George Hodgson",
        "Centro Escolar Francisco Hernandez De Cordoba",
        "Centro Escolar Jose Dolores Estradas",
        "Centro Escolar Juan De Dios",
        "Centro Escolar La Perla",
        "Centro Escolar Juan Pablo Ii",
        "Centro Escolar La Esperanza",
        "Centro Escolar Loma Linda",
        "Centro Escolar La Esperanzita",
        "Centro Escolar La Bendicion",
        "Centro Escolar La Estrella",
        "Centro Escolar Krisimbila",
        "Centro Escolar Neysi Rios",
        "Centro Escolar Las Mariposas",
        "Centro Escolar Mons.Salvador Schetfer",
        "Centro Escolar La Sorpresa",
        "Centro Escolar Las Carmensitas",
        "Centro Escolar Luz Y Vida",
        "Centro Escolar Las Maravillas",
        "Centro Escolar Las Delicias",
        "Centro Escolar Luz De La Selva",
        "Centro Escolar Nacuna",
        "Centro Escolar Luz En La Selva",
        "Centro Escolar Nelson Guill\U00c9n",
        "Centro Escolar Rafaela Herrera #2",
        "Centro Escolar Ni\U00d1os Del Futuro",
        "Centro Escolar Milagro De Dios",
        "Centro Escolar Punta De Aguila",
        "Centro Escolar Salomon De La Selva",
        "Centro Escolar Primeros Pasos #2",
        "Centro Escolar Rosario Murillo",
        "Centro Escolar Ruben Dario",
        "Centro Escolar Rayo De Luz",
        "Centro Escolar Sagrado Corazon",
        "Centro Escolar San Francisco",
        "Centro Escolar San Pedro",
        "Centro Escolar San Isidro",
        "Centro Escolar San Martin",
        "Centro Escolar San Antonio",
        "Centro Escolar San Ramon Der Nueva Esperanza",
        "Centro Escolar San Juan De La Salle",
        "Centro Escolar Santa Rosa",
        "Centro Escolar Silvestre Duarte",
        "Centro Escolar San Antonio Wilinki",
        "Centro Escolar Villa Nueva N\U00ba 3",
        "Centro Escolar San Mateo",
        "Cristobal Col\U00d3n",
        "Centro Escolar Santa Ana",
        "Centro Escolar Santa Rosa",
        "Centro Escolar Santa Martha",
        "Centro Escolar Santa Elena",
        "Centro Escolar Virgen Del Rosario",
        "El Eden No. 2",
        "Centro Escolar Zeledon",
        "Centros Escolar San Jose",
        "Edwin Baltodano",
        "Escuela Dinamarca",
        "Escuela Comunal De Old Bank",
        "Colegio Publico San Luis",
        "Divino Ni\U00d1o",
        "Esc. Jose Cecilio Del Valle",
        "Escuela Dinamarca",
        "Escuela Divina Providencia",
        "Emmanuel Los Pipitos",
        "El Gorrion #2",
        "Cristianos Unidos",
        "Escuela Campo Verde Rio Maiz",
        "Escuela Barbie Henriquez Cash",
        "Escuela Especial Aaron Hodgson",
        "Fuente Del Futuro",
        "Escuela San Luis",
        "Escuela Menorca",
        "Escuela Publica Paz Y Esperanza",
        "El Retiro",
        "Escuela Santa Rosa",
        "El Esfuerzo",
        "Instituto Clemente Beily",
        "Instituto Nacional Santos Escobar Carmona",
        "Escuela Publica San Pedro",
        "Escuela Santa Fe #2",
        "Escuela Virgen Del Carmen",
        "La Fortuna Santa Fe",
        "Guadalupe",
        "Ivan Dixon",
        "Instituto Nacional Publico Prudencio Obando",
        "Intituto Nacional Cristobal Colon",
        "Instituto Horatio Hodgson High School",
        "La Estrellita Piedra Azul",
        "Las Brisas",
        "Mis Primeros Pasos",
        "Miraflores",
        "Jose De La Cruz Mena",
        "Los Robles",
        "Loma Linda",
        "Nueva Jerusalen",
        "Preescolar La Estrellita",
        "Nuevo Amanecer",
        "Northon Martinez",
        "Mira Mar",
        "Pre Escolar San Mateo",
        "Ruben Dario - Aguas Gatas",
        "Nueva Esperanza",
        "Ruben Dario",
        "San Jose N\U00b01",
        "San Luis",
        "Primeros Pasos",
        "San Mariano (Carlos F. Amador)",
        "Sagrada Familia",
        "Ruben Dario Sarmiento",
        "San Gabriel",
        "Santa Teresa",
        "San Mateo",
        "San Martin",
        "Santa Isabel",
        "Santa Rosa",
        "Centro Escolar Fray Bartolome De Las Casas",
        "Centro Escolar Alberto Benjamin",
        "Centro Escolar Buena Esperanza",
        "Centro Escolar Big Creek Nacuna",
        "Centro Escolar El Triunfo #2",
        "Centro Escolar Benjamin Cuadra",
        "Centro Escolar El Venado",
        "Centro Escolar Monse\U00d1or Mateo",
        "Centro Escolar La Maravilla",
        "Centro Escolar Las Carmelitas",
        "Centro Escolar Neylin Alvarado",
        "Centro Escolar Nueva Luz #2",
        "Centro Escolar Ntra Se\U00d1ora Del Rosario",
        "Centro Escolar Las Nubes",
        "Centro Escolar Mar\U00cda Jos\U00c9",
        "Centro Escolar Luz De La Esperanza",
        "Centro Escolar Luz Del Futuro",
        "Centro Escolar Santa Teresa",
        "Centro Escolar Santa Fe",
        "Centro Escolar San Sebastian",
        "Centro Escolar Ruben Dario",
        "Centro Escolar Sendero De Luz",
        "Centro Escolar Poza Azul",
        "Centro Escolar Shal\U00d3n",
        "Centro Escolar Sinai Ca\U00d1o La Papaya",
        "Centro Escolar Rafaela Herrera #1",
        "El Hogar",
        "Instituto Nacional Nuevo Amanecer",
        "Montes Verdes",
        "Reina De La Paz",
        "Monte Crique Punta Gorda",
        "Milagro De Jesus",
        "San Jose",
        "Santa Maria",
        "Ruben Dario N\U00b02",
        "Salomon Ibarra Mayorga",
        "Colegio Cristiano Verbo",
        "Rub\U00c9n Dar\U00cdo (Atlanta)",
        "San Jose N\U00ba2",
        "El Esfuerzo",
        "C.D.I Mirna Viales Alvarez",
        "Centro Escolar Betesda",
        "Centro Escolar San Sebastian No.6",
        "Centro Escolar San Antonio",
        "Centro Escolar Nuevo Oriente",
        "Centro Escolar Santa Elena",
        "Corazon Del Padre",
        "Centro Escolar San Jos\U00c9",
        "Colegio San Marco Anglicana",
        "Colegio Moravo De Secundaria",
        "Centro Infantil Ni\U00d1o Jesus De Praga",
        "Colegio Adventista Del 7mo. Dia Atl\U00c1ntico Sur",
        "Colegio San Marcos Secundaria",
        "Escuela Adventista De Bluefields",
        "El Triunfo",
        "Luz De Esperanza",
        "Nueva Esperanza",
        "La Escuelita",
        "Monte De Los Olivos",
        "Inmaculada Concepci\U00d3n",
        "San Benito",
        "Primaria Colegio Moravo",
        "Preescolar Bethel Buen Comienzo",
        "Preescolar Arcoiris Caribe\U00d1os",
        "Preescolar Jardin Coste\U00d1o",
        "Sagrada Familia No. 2",
        "Centro Escolar San Jorge",
        "Escuela Bautista",
        "Colegio Madre Del Divino Pastor",
        "Centro Escolar Cristo Rey",
        "Santa Terecita",
        "San Jose",
        "Centro Escolar Nuevo Palestina",
        "Centro Escolar Ruben Dario",
        "Pre Escolar Nicaraguita",
        "Nellys Jiron",
        "Centro Escolar Deyling Olivar Betancourth",
        "Centro Escolar El Lagerito",
        "Centro Escolar El Buen Consuelo",
        "Centro Escolar Buena Vista",
        "29 De Junio",
        "Amalia Estrada",
        "Andres Castro",
        "Alfonso Cortez",
        "Arlenys Davila",
        "Centro Escolar  Prof.Paulino Halsall R",
        "Centro Escolar Alfonso Cortez",
        "Carlo Delgado",
        "Centro Escolar 15 De Sept",
        "Buena Vista",
        "Benjam\U00cdn Zeled\U00d3n",
        "Centro Escolar Asuncion Lopez",
        "Centro Escolar Bayardo Lacayo Rocha",
        "Centro Escolar 18 De Enero 1867",
        "Centro Escolar Albertina Sevilla Sevilla",
        "Centro Escolar Azul 1888",
        "Centro Escolar Buena Esperanza",
        "Centro Escolar Alejandro Vegas Matus",
        "Centro Escolar Augusto Cesar Sandino",
        "Centro Escolar Cantos De Vida Y Esperanza",
        "Centro Escolar Alfonso Valle",
        "Centro Escolar Andres Castro",
        "Centro Escolar Bienvenidos Al Nuevo Amanecer",
        "Centro Escolar Corina Obando Palma",
        "Centro Escolar Cristo Rey",
        "Centro Escolar Divino Ni\U00d1o",
        "Centro Escolar Carlos Darwin",
        "Centro Escolar Benjamin Francisco Zeledon Rodriguez",
        "Centro Escolar El Buen Samaritano",
        "Centro Escolar Carlos Mantica",
        "Centro Escolar El Cisne",
        "Centro Escolar El Buen Maestro",
        "Centro Escolar El Consuelo",
        "Centro Escolar El Naranjito",
        "Centro Escolar El Manantial",
        "Centro Escolar Jorge Salazar",
        "Centro Escolar Enmanuel Mongalo Y Rubio",
        "Centro Escolar El Triunfo De Los Ni\U00d1os",
        "Centro Escolar Fatima Del Rosario",
        "Centro Escolar Enmanuel Mongalo N\U00ba2",
        "Centro Escolar Marisol Malea\U00d1o Espinoza",
        "Centro Escolar Jose Cecilio Del Valle",
        "Centro Escolar Josefa Toledo De Aguerri",
        "Centro Escolar Fco Aoron Jose Flores",
        "Centro Escolar Jose Bravo",
        "Centro Escolar Humberto Hernandez",
        "Centro Escolar La Esperancita",
        "Centro Escolar Gaspar Garcia Laviana",
        "Centro Escolar Jose Santos Zelaya",
        "Centro Escolar Juan Ramon Jimenez",
        "Centro Escolar La Trinidad N\U00ba3",
        "Centro Escolar Martin Lutero",
        "Centro Escolar Los Manantiales",
        "Centro Escolar Luz Del Saber",
        "Centro Escolar Los Laureles",
        "Centro Escolar Mauricio Cajina",
        "Centro Escolar Manuel Esteban Tellez Baez",
        "Centro Escolar Miguel Angel De Castilla",
        "Centro Escolar Pedro Joaquin Chamorro N\U00ba2",
        "Centro Escolar Las Bocanas",
        "Centro Escolar Maximo Cortedano Palma",
        "Centro Escolar Nuevo Amanecer",
        "Centro Escolar Nueva Esperanza",
        "Centro Escolar Rafaela Herrera",
        "Centro Escolar Rafaela Rosales Aguilar",
        "Centro Escolar Pablo Smith N\U00ba2",
        "Centro Escolar Omar Perez",
        "Centro Escolar Ruben Dario No. 1",
        "Centro Escolar Pablo Antonio Cuadra",
        "Centro Escolar Sagrado Corazon De Jesus",
        "Centro Escolar Pedrito Antony Hernandez",
        "Centro Escolar Ruben Dario Sarmiento",
        "Centro Escolar San Francisco",
        "Centro Escolar Rigoberto Cabezas Figueroa",
        "Centro Escolar Pedro Joaquin Chamorro",
        "Centro Escolar Rafaela Contrera",
        "Centro Escolar Santa Isabel",
        "Centro Escolar Santa Teresita",
        "Centro Escolar Selva Verde",
        "Centro Escolar Vigarny Flores Castle",
        "Centro Escolar San Esteban",
        "Cesar Augusto Salinas",
        "Centro Escolar Violeta Barrios De Chamorro",
        "El Divino Creador",
        "El Progreso",
        "El Gavil\U00c1n",
        "El Triunfo",
        "Cristo Rey",
        "Divino Rostro",
        "El Buen Pastor",
        "El Carmen",
        "El Jardin",
        "Esc. Delia Arellano",
        "Coraz\U00d3n De Mar\U00cda",
        "El Chotecito",
        "Gloria Elena Jarquin Bracamonte",
        "Esc. 12 De Septiembre",
        "Esc. Ernesto Cardenal",
        "Gracias A Dios",
        "Esc. 12 De Octubre",
        "Escuela Mi Futuro",
        "Instituto  Ruben Dario",
        "Felix Leonidas Garcia La Florida",
        "Escuela Luz Del Recuerdo",
        "Francisco Leon",
        "Esmirna",
        "La Fraternidad",
        "Francisco Moraz\U00c1n",
        "Jose Dolores Estrada",
        "La Estrella No. 2",
        "Jose Miguel Torrez",
        "Jorge Isaac Carballo",
        "Las Maravillas",
        "La Flor",
        "Los Mantelitos",
        "Maestro Gabriel",
        "Los Limones",
        "Maria Montesori",
        "Nueva Esperanza",
        "Maria Nela Callejas",
        "Maria Perez",
        "Nueva Palestina",
        "Mata De Maiz",
        "Mar\U00cda Dolores De Alem\U00c1n",
        "Marvin Oporta Quintanilla",
        "Los Angeles",
        "Luz De La Esperanza",
        "Miravalle #2",
        "Pedro Joaquin Chamorro (Las Milpas)",
        "Rafaela Herrera N\U00ba 3",
        "Rafael Miranda Padilla",
        "San Luis",
        "San Pablo",
        "Progreso Santa Lucia",
        "Santa Martha",
        "Rub\U00c9n Dario Sarminto No.2",
        "Salom\U00d3n De La Selva - Sardina",
        "San Jose",
        "San Jos\U00c9",
        "San Pablo",
        "San Sebastian",
        "Santa Ana",
        "Santa Elena",
        "Santa Luc\U00cda - Los Ranchitos",
        "Santa Rosa #3",
        "Santa Rosa #2",
        "Santa Rosa",
        "Santa Isabel (El Tigre)",
        "San Ram\U00d3n",
        "Centro Escolar 14 De Sept",
        "Centro Escolar Ernesto Sanchez Diaz",
        "Centro Escolar Cristo Rey",
        "Centro Escolar Diriangen",
        "Centro Esc. Concepcion De San Luis De Providencia",
        "Centro Escolar Carlos Vargas Lopez",
        "Centro Escolar German Pomares",
        "Centro Escolar Cristobal Colon",
        "Centro Escolar Carlos Fonseca Amador",
        "Centro Escolar Miguel Larreynaga",
        "Centro Escolar La Ternura",
        "Centro Escolar Las Delicias",
        "Centro Escolar Josefa Toledo De Aguirre",
        "Centro Escolar Las Primaveras N\U00ba2",
        "Centro Escolar Luz De La Selva",
        "Centro Escolar Santa Isabel N\U00ba2",
        "Centro Escolar Prosas Profanas",
        "Centro Escolar Salomon Ibarra Mayorga",
        "Centro Escolar Ruben Dario",
        "Centro Escolar Ruben Dario",
        "Fatima Del Rosario",
        "Escuela Rural San Juan",
        "Escuela Manteles Verdes",
        "Escuela Francisco Morazan #2",
        "Jerusalen",
        "Pablo Antonio Cuadra No. 3",
        "Las Brisas",
        "Las Vegas",
        "San Antonio",
        "San Rafael",
        "Ruben Dario #2",
        "Tomasa Damaris Rueda Calero",
        "San Francisco",
        "Armenia Del Valle",
        "Centro Escolar El Progreso # 2",
        "Centro Escolar Rafael A. Salmeron B.",
        "Centro Escolar Divino Redentor",
        "San Blas",
        "El Alamo",
        "Antonio De Nebrija",
        "Cardenal Cisneros",
        "Cervantes",
        "Daoiz Y Velarde",
        "Sagrado Corazon De Jesus",
        "San Felipe Neri",
        "Escuelas Pias",
        "Emperador Fernando",
        "Santa Maria De La Providencia",
        "Complutense",
        "Nuestra Señora Del Val",
        "Doctora De Alcala",
        "San Gabriel",
        "San Ignacio De Loyola",
        "Minerva",
        "Alonso De Avellaneda",
        "Calasanz",
        "Lope De Vega",
        "Antonio Machado",
        "Infanta Catalina",
        "Federico Garcia Lorca",
        "Antonio Machado",
        "San Pedro Apostol",
        "San Antonio",
        "Juan Xxiii",
        "Liceo Europeo",
        "Francisco Giner De Los Rios",
        "Daoiz Y Velarde",
        "Bienaventurada Virgen Maria",
        "Colegio Suizo De Madrid (Suizo)",
        "Carmen Conde",
        "Nuestra Señora De Rihondo",
        "Santisima Trinidad",
        "Nuestra Señora De Los Remedios",
        "Amor De Dios",
        "La Inmaculada",
        "Virgen Del Remedio",
        "Centro Educativo Villa De Alcorcon",
        "Daniel Martin",
        "Parroco D. Victoriano",
        "San Pablo-Ceu",
        "Nuestra Señora De Fatima",
        "Obispo Moscoso",
        "Santa Quiteria",
        "San Jose De Calasanz",
        "Virgen Del Puerto",
        "Sagrada Familia",
        "San Pascual",
        "Vicente Aleixandre",
        "Apostol Santiago",
        "Arco Iris Abastos",
        "Loyola",
        "San Isidro",
        "Domenico Scarlatti",
        "Principe De Asturias",
        "Jorge Manrique",
        "Nuestra Señora De La Milagrosa",
        "El Carrascal",
        "San Juan Bautista",
        "El Torreon",
        "Juan Ramon Jimenez",
        "Belmonte De Tajo",
        "Principe Don Felipe",
        "Virgen De Europa",
        "Trinity College Boadilla",
        "San Sebastian",
        "Batalla De Brunete",
        "Peñalta",
        "Gsd International School Buitrago",
        "Montelindo",
        "Pico De La Miel",
        "Eugenio Muro",
        "Federico Garcia Lorca",
        "Miguel Delibes",
        "Tome Y Orgaz",
        "Suarez Somonte",
        "Via Romana",
        "Regina Assumpta",
        "Ventura Rodriguez",
        "Juan Carlos I",
        "Virgen Del Consuelo",
        "San Juan De Dios",
        "Villa De Cobeña",
        "Apis Aurelia",
        "Seis De Diciembre",
        "Soledad Sainz",
        "Virgen De Los Remedios",
        "Marques De Santillana",
        "Internacional Pinosierra",
        "Virgen De La Paz",
        "Cañada Real",
        "Santisima Trinidad",
        "Miguel Delibes",
        "Jaime Ferran",
        "Virgen De La Almudena",
        "San Pablo",
        "Mama Juanita",
        "Virgen Del Henar",
        "San Esteban",
        "Miguel Catalan",
        "Nuestra Señora De La Soledad",
        "Hermanos Ortiz De Zarate",
        "Angel Berzal Fernandez",
        "Felipe Ii",
        "Padre Gerardo Gil",
        "Carlos Ruiz",
        "San Esteban",
        "Martina Garcia",
        "Alarilla",
        "Carlos Ruiz",
        "San Gregorio",
        "La Alhondiga",
        "Ortiz Echagüe",
        "Santa Margarita Maria Alacoque",
        "Sagrado Corazon",
        "Liceo Juan De La Cierva I",
        "Mengual",
        "Santa Teresa",
        "Jesus Nazareno",
        "San Jose",
        "San Sebastian",
        "Matematico Puig Adam",
        "La Inmaculada-Padres Escolapios",
        "Divina Pastora",
        "Seseña Y Benavente",
        "Alarnes",
        "San Jose De Calasanz",
        "Ciudad De Madrid",
        "Garcilaso De La Vega",
        "La Salle",
        "Alejandro Rubio",
        "Colegio Juan Pablo Ii Y La Inmaculada",
        "Villa De Guadarrama",
        "Virgen De La Encina",
        "Hermanos Tora",
        "Calderon De La Barca",
        "Lepanto",
        "Marques De Leganes",
        "La Inmaculada",
        "Liceo San Pablo",
        "El Salvador",
        "Gonzalo De Berceo",
        "Victor Pradera",
        "Miguel De Cervantes",
        "Ortega Y Gasset",
        "Aben Hazam",
        "Jose De Churriguera",
        "Luis Vives",
        "Maria Zambrano",
        "Duque De Alba",
        "Montfort International School",
        "Cervantes",
        "Damaso Alonso",
        "Cervantes Baby",
        "Francisco Alcantara Ceramica",
        "Isaac Albeniz",
        "Ciudad De Jaen",
        "Vasco Nuñez De Balboa",
        "Escuelas Aguirre",
        "Agustina Diez",
        "Alberto Alcocer",
        "Alfonso X El Sabio",
        "Antonio Machado",
        "De Practicas Asuncion Rincon",
        "Azorin",
        "Barcelona",
        "Beata Maria Ana De Jesus",
        "Bolivia",
        "Escuelas Bosque",
        "Capitan Cortes",
        "Cervantes",
        "Ciudad De Los Angeles",
        "Ciudad Pegaso",
        "Claudio Moyano",
        "Conde De Romanones",
        "Cristobal Colon",
        "Divino Corazon",
        "Emilia Pardo Bazan",
        "Francisco Fatou",
        "Francisco De Quevedo",
        "Francisco Ruano",
        "Fray Junipero Serra",
        "Fray Pedro Ponce De Leon",
        "Reina Victoria",
        "Gonzalo Fernandez De Cordoba",
        "Gustavo Adolfo Becquer",
        "Haiti",
        "Hermanos Pinzon",
        "Hernan Cortes",
        "Honduras",
        "Hospital Del Niño Jesus",
        "Maria Soriano",
        "Isaac Peral",
        "Luis Bello",
        "Jaime Balmes",
        "Javier De Miguel",
        "Joaquin Dicenta",
        "Jose Maria De Pereda",
        "Jovellanos",
        "Juan De La Cierva",
        "Juan Ramon Jimenez",
        "Juan Sebastian Elcano",
        "Lopez Vicuña",
        "Luis De Gongora",
        "Manuel De Falla",
        "Colegio Diocesano Maria Inmaculada - Mogambo",
        "Colegio Diocesano Maria Inmaculada - Joaquin Turina",
        "Colegio Diocesano Maria Inmaculada - Luis Ruiz",
        "Jorge Manrique",
        "Marques De Marcenado",
        "Mater Amabilis",
        "Amos Acero",
        "Mejico",
        "Mendez Nunez",
        "Menendez Y Pelayo",
        "Menendez Pidal",
        "Mesonero Romanos",
        "Navas De Tolosa",
        "Eduardo Rojo",
        "Nuestra Señora De La Concepcion",
        "Padre Coloma",
        "Padre Mariana",
        "Padre Piquer",
        "Padre Poveda",
        "Parque Aluche",
        "Peru",
        "Pinar Del Rey",
        "Pio Xii",
        "Puerto Rico",
        "Gonzalo De Berceo",
        "Ramiro De Maeztu",
        "Regimiento Inmemorial Del Rey",
        "Republica Del Brasil",
        "Republica Dominicana",
        "Republica De Ecuador",
        "Republica Del Paraguay",
        "Republica Del Uruguay",
        "Republica De Venezuela",
        "Los Rosales",
        "Rufino Blanco",
        "Sagunto",
        "San Carlos",
        "San Eugenio Y San Isidro",
        "San Ignacio De Loyola",
        "San Ildefonso",
        "San Isidoro",
        "San Juan De La Cruz",
        "San Pablo",
        "Santa Ana Y San Rafael",
        "Santa Maria",
        "Santo Domingo",
        "Tirso De Molina",
        "La Alameda",
        "Vedruna",
        "Arcipreste De Hita",
        "Alameda De Osuna",
        "El Ave Maria",
        "Beata Filipina-Fund.Feliciana Viertola",
        "Eipa Escuela Infantil Parque De Las Avenidas",
        "Comendadoras De Santiago",
        "Madres Concepcionistas",
        "Cristo Rey",
        "Cristo Rey",
        "Luz Casanova Embajadores",
        "Nazaret-Oporto",
        "Sagrado Corazon De Jesus",
        "Colegio Nuevo Equipo",
        "San Luis-Felca",
        "Fundacion Caldeiro",
        "Hastings School (Britanico)",
        "Jesus Maestro",
        "Jesus Maria",
        "Direccion Area Territorial Madrid-Capital",
        "Madre De Dios",
        "Maria Inmaculada",
        "Maria Reina",
        "Maria Reina",
        "Mater Clementissima",
        "Mater Inmaculata",
        "Direccion Area Territorial Madrid-Oeste",
        "La Merced",
        "Mirasierra",
        "Blanca De Castilla",
        "Nuestra Señora Del Buen Consejo",
        "Nuestra Señora Del Buen Consejo",
        "Nuestra Señora De Los Dolores",
        "Nuestra Señora De Fatima",
        "Nuestra Señora De Las Maravillas",
        "Obra So.N.S.Montserrat-S.Simon Y S.Judas",
        "Direccion Area Territorial Madrid-Este",
        "Nuestra Señora De Las Nieves",
        "Nuestra Señora De La Paz",
        "Nuestra Señora Del Pilar",
        "Nuestra Señora Del Pilar",
        "Liceo Oroquieta",
        "El Osito De Luis De Larrainza",
        "El Porvenir",
        "El Prado",
        "Purisima Concepcion",
        "Ramon Y Cajal",
        "Reina De Los Angeles",
        "El Ardal",
        "Sagrado Corazon",
        "Sagrado Corazon",
        "Sagrado Corazon",
        "Santa Maria Micaela",
        "La Salle-Sagrado Corazon",
        "Sagrados Corazones",
        "Enriqueta Aymer",
        "San Antonio",
        "San Buenaventura",
        "Arturo Soria",
        "San Eulogio",
        "San Jaime Apostol",
        "San Javier",
        "San Jose",
        "San Jose",
        "Instituto San Jose",
        "San Jose De Cluny",
        "San Juan Bautista",
        "Direccion Area Territorial Madrid-Sur",
        "San Rafael Arcangel-Santa Luisa",
        "San Roque",
        "San Viator",
        "San Vicente",
        "Santa Elizabeth",
        "Santa Gema Galgani",
        "Real Colegio Santa Isabel-La Asuncion",
        "Santa Maria",
        "Santa Maria De Los Apostoles",
        "Santa Maria Del Pilar",
        "Santa Maria De Los Pinos",
        "Santa Maria Del Valle Cep",
        "Colegio Escuelas Santisimo Sacramento",
        "Santisimo Sacramento",
        "Santo Angel De La Guarda",
        "Santo Angel De La Guarda",
        "Teide Iv",
        "Virgen De Begoña",
        "Virgen Del Pilar",
        "Colegio A La Par",
        "Portugal",
        "Tomas Breton",
        "Amador De Los Rios",
        "Aravaca",
        "Asuncion Cuestablanca",
        "Santa Rafaela Maria",
        "Carlos V",
        "Carmen Cabezuelo",
        "Concepcion Arenal",
        "Doctor Conde Arruga",
        "Costa Rica",
        "Cuba",
        "Divino Maestro",
        "Doctor Federico Rubio",
        "Ermita Del Santo",
        "Felipe Ii",
        "Fernandez Moratin",
        "Fernando El Catolico",
        "Francisco De Luis",
        "Garcia Morente",
        "Pi I Margall",
        "Francisco De Goya",
        "Isabel La Catolica",
        "Joaquin Costa",
        "Jose Calvo Sotelo",
        "Legado Crespo",
        "Lepanto",
        "Lope De Vega",
        "Manuel Bartolome Cossio",
        "Manuel Sainz De Vicuña",
        "Marcelo Usera",
        "Miguel Blasco Vilatela",
        "Miguel De Unamuno",
        "Manuel Nuñez De Arenas",
        "Antonio Moreno Rosales",
        "Nuestra Señora De La Almudena",
        "Leopoldo Alas",
        "Palacio Valdes",
        "Republica De Panama Nº 1",
        "Patriarca Obispo Eijo Garay",
        "Ramon Gomez De La Serna",
        "Real Armada",
        "Republica De Colombia",
        "Republica De Chile",
        "Republica De El Salvador",
        "San Cristobal",
        "San Juan Bosco",
        "Vazquez De Mella",
        "Afuera Iii A",
        "Patrocinio De Maria",
        "Amor De Dios",
        "Amor Misericordioso",
        "Amoros",
        "Arcangel",
        "Santa Beatriz De Silva",
        "Cardenal Spinola",
        "El Carmelo Teresiano",
        "Central",
        "Liceo Sorolla B",
        "Ciudad De Los Muchachos",
        "Liceo Consul",
        "Corazon Inmaculado",
        "Corazon De Maria",
        "Ciudad De Cordoba",
        "Decroly",
        "Divina Pastora",
        "Colegio Institucion Del Divino Maestro",
        "Trilema Avenida America",
        "Fem School",
        "Tajamar",
        "Montpellier",
        "Santa Maria De La Hispanidad",
        "Fray Luis De Leon",
        "Gamo Diana",
        "Los Robles",
        "Hispano Aleman",
        "La Inmaculada-Marillac",
        "British Council School (Britanico)",
        "Alenta",
        "Jesus Maria",
        "Jardin Kinderland",
        "Luz Casanova",
        "Luz Casanova",
        "Salesianos Atocha",
        "Maria Corredentora",
        "Maria Cristina",
        "Maria Reina",
        "Marin Amat",
        "Menesiano",
        "Madres Mercedarias De D. Juan De Alarcon",
        "La Milagrosa",
        "Minerva",
        "Montealto",
        "Natividad De Nuestra Señora",
        "Nuestra Señora De Los Angeles",
        "Asuncion-Vallecas",
        "Nuestra Señora Del Carmen",
        "Colegio La Milagrosa",
        "Nuestra Señora De La Consolacion",
        "Nuestra Señora De Las Escuelas Pias",
        "Calasancio Nuestra Señora De Las Escuelas Pias",
        "Nuestra Señora De Las Escuelas Pias",
        "Nuestra Señora De Gracia",
        "Liceo Madariaga",
        "Real Colegio Nuestra Señora De Loreto",
        "Nuestra Señora De La Merced",
        "Nuestra Señora De La Merced",
        "Nuestra Señora De La Merced",
        "Montserrat",
        "Nuestra Señora De La Paloma",
        "Nuestra Señora Del Recuerdo",
        "Huerfanos De La Armada",
        "Wisdom School Madrid",
        "Nuestra Señora Del Sagrado Corazon",
        "Nuestra Señora Santa Maria",
        "Nuestra Señora De Las Victorias",
        "Nuestra Señora De Las Victorias",
        "Patrocinio De San Jose",
        "Pureza De Maria",
        "Rafaela Ybarra",
        "Raimundo Lulio",
        "Trilema Safa",
        "Sagrada Familia",
        "Sagrada Familia De Urgel",
        "Sagrado Corazon",
        "Sagrado Corazon De Jesus",
        "Sagrado Corazon De Jesus",
        "Sagrados Corazones",
        "Paraiso Sagrados Corazones",
        "Colegio La Salle San Rafael",
        "La Salle",
        "San Alfonso",
        "El Espinillo ",
        "San Fermin",
        "San Francisco De Asis",
        "San Jose",
        "San Jose De Begoña",
        "San Jose Del Parque",
        "Colegio Aleman De Madrid (Aleman)",
        "Salesianos Paseo De Extremadura",
        "San Patricio",
        "San Pedro",
        "San Roque",
        "Santa Catalina De Sena",
        "Santa Francisca Javier Cabrini",
        "Santa Isabel",
        "Fundacion Santamarca",
        "Santa Maria Del Bosque",
        "Santa Maria Del Carmen",
        "Santa Maria De Los Rosales",
        "Santa Rita",
        "San Gabriel",
        "Santo Angel",
        "Santo Domingo",
        "Santo Domingo Savio",
        "Colegio Senara",
        "Vedruna",
        "Virgen De Atocha",
        "Colegio Virgen De Mirasierra",
        "Colegio San Pedro Apostol",
        "Centro Cultural Elfo",
        "Stella Maris",
        "Colegio Santa Maria Del Camino",
        "Colegio Internacional Nicoli",
        "Claret",
        "Liceo Iberico",
        "Agrupacion Escolar Europa",
        "San Agustin",
        "Valdeluz",
        "Cumbre-Oxford",
        "Azorin",
        "Nuestra Señora De La Providencia",
        "Nuestra Señora De La Estrella",
        "Obispo Perello",
        "Valdebernardo",
        "El Cid",
        "Divina Pastora",
        "Inmaculada Concepcion",
        "Los Lapazares",
        "Reinado Del Corazon De Jesus",
        "Sagrado Corazon",
        "Centro Cultural Salmantino",
        "San Alberto Magno",
        "Colegio Nuestra Señora De Loreto Fesd",
        "Mater Purissima",
        "Los Alamos",
        "Los Pinos",
        "Siglo Xxi",
        "Nebrija-Rosales",
        "Liceo Versalles",
        "San Jose",
        "San Jose",
        "Santa Cruz",
        "Union Chretienne De St.Chaumond (Franc.)",
        "Nuestra Señora Del Pilar",
        "San Martin",
        "Parque Conde De Orgaz",
        "Agora",
        "Santa Teresa De Jesus",
        "Santamarca",
        "Santa Engracia",
        "Catedra De Pediatria, Hospital Clinico",
        "Ortega Y Gasset",
        "Alcalde De Mostoles",
        "Amadeo Vives",
        "Instituto Politecnico N.1 Del Ejercito",
        "Emilio Castelar",
        "Doctor Tolosa Latour",
        "Arcipreste De Hita",
        "San Cristobal De Los Angeles",
        "Carlos Maria Rodriguez De Valcarcel",
        "Martinez Montañes",
        "Ciudad De Guadalajara",
        "Afuera Ii",
        "Gonzalez Cañadas",
        "Ciudad De Zaragoza",
        "San Bernardo",
        "Aries",
        "Diaz Balaguer",
        "Joaquín Turina",
        "Vox",
        "Estudio",
        "Centro Cultural Palomeras",
        "La Inmaculada",
        "Maria Inmaculada",
        "El Lago",
        "Fec Santa Joaquina De Vedruna",
        "San Fernando",
        "Francisco Arranz",
        "Ciudad De Badajoz",
        "Tirso De Molina",
        "San Miguel",
        "Nuestra Señora De Los Dolores",
        "San Benito",
        "San Ramon Y San Antonio",
        "Altair, Colegio Internacional",
        "Maria Virgen",
        "Agustiniano",
        "Lope De Vega",
        "Dario Estudio",
        "Barajas",
        "Centro De Estudios Castilla",
        "Santa Barbara",
        "La Salle-La Paloma-Fundacion Lara",
        "Bristol",
        "Sagrado Corazon",
        "Gregorio Marañon",
        "Chamberi",
        "Casa De La Virgen",
        "San Jose-Lucero",
        "Barrio Simancas",
        "Lourdes",
        "Mater Salvatoris",
        "Virgen De La Paloma",
        "Escuela Profesional Javeriana",
        "Santa Maria Del Yermo",
        "Maria Auxiliadora",
        "Colegio Ceu San Pablo De Claudio Coello",
        "Juan Zaragueta",
        "Conde De Orgaz",
        "Carlos Iii",
        "San Blas",
        "Gómez Moreno",
        "Rey Pastor",
        "Vallecas I",
        "Carlos Sainz De Los Terreros",
        "Ciudad De Valencia",
        "Enrique Tierno Galvan",
        "Pio Baroja",
        "Parque Aluche",
        "Eijo Y Garay",
        "Nuestra Señora Del Lucero",
        "Nuestra Señora De La Almudena",
        "Tetuan De Las Victorias",
        "Cardenal Herrera Oria",
        "Lorenzo Luzuriaga",
        "Beatriz Galindo",
        "Isabel La Catolica",
        "Juan De La Cierva",
        "Cardenal Cisneros",
        "San Isidro",
        "Emperatriz Maria De Austria",
        "Calderon De La Barca",
        "Vista Alegre",
        "Pintor Rosales",
        "Jorge Guillen",
        "C.R.E. Antonio Vicente Mosquete",
        "Colegio Madrid Pinar",
        "Arquitecto Gaudi",
        "Marques De Suanzes",
        "Princesa Sofia",
        "Francisco Del Pozo",
        "Fundacion Goyeneche",
        "Antonio De Nebrija",
        "Pacifico",
        "Filosofo Seneca",
        "Joaquin Turina",
        "Concha Espina",
        "Rabindranath Tagore",
        "Bravo Murillo",
        "La Palma",
        "Luis Cernuda",
        "Esperanza",
        "Doctor Severo Ochoa",
        "Pio Baroja",
        "Daniel Vazquez Diaz",
        "Jose Ortega Y Gasset",
        "Palomeras Vallecas",
        "Garcia Morato",
        "Gran Capitán",
        "Afuera I",
        "Monseñor Alves Bras",
        "La Anunciata",
        "Bernadette",
        "Guzman El Bueno",
        "Centro Nuevo De Pedagogia",
        "Cumbre",
        "Estudio 3",
        "Lycee Français (Frances)",
        "La Inmaculada",
        "Mirasol",
        "La Natividad",
        "Los Olmos",
        "Las Naciones",
        "Carmen Martin Gaite",
        "Santa Monica",
        "Teide Ii",
        "Trabenco",
        "Vida",
        "Bienaventurada Virgen Maria",
        "Buenafuente",
        "Institucion Profesional Salesiana",
        "Nervion",
        "Nuestra Señora De Fatima",
        "Primero De Mayo",
        "Cervantes",
        "Colegio De Jesus",
        "Jose Ramon Otero",
        "Nuestra Señora De Las Delicias",
        "Ciudad Escolar",
        "San Pio X",
        "Virgen De Lourdes",
        "Maria Auxiliadora",
        "Virgen De La Peña Sacra",
        "San Sebastian",
        "Jarama",
        "Vicente Aleixandre",
        "San Pablo",
        "Nuestra Señora Del Remolino",
        "Divino Maestro",
        "Santa Teresa",
        "San Miguel Arcangel",
        "Claudio Vazquez",
        "Andres Torrejon",
        "Beato Simon De Rojas",
        "Liceo Villa Fontana",
        "Villa De Mostoles",
        "Balmes",
        "La Inmaculada",
        "Antonio Hernandez",
        "Juan Perez Villaamil",
        "Colegio Villaeuropa",
        "Antusana",
        "Federico Garcia Lorca",
        "Felipe Trigo",
        "Nuestra Señora Del Carmen",
        "Principe De Asturias",
        "Carlos Ruiz",
        "San Luis Gonzaga",
        "Carmen Martin Gaite",
        "Isabel La Catolica",
        "Internacional Eurovillas",
        "Juan De Goyeneche",
        "Virgen De La Ribera Fund. Hnos.",
        "Ciudad De Merida",
        "Magerit",
        "Virgen Del Carmen",
        "Nuestra Señora Del Castillo",
        "Isabel La Catolica",
        "El Prado",
        "Nuestra Señora De La Providencia",
        "Sagrada Familia",
        "Santo Domingo De Silos",
        "Los Angeles",
        "Asuncion De Nuestra Señora",
        "Retamar",
        "San Jose De Cluny",
        "Hogar Del Buen Consejo",
        "San Luis De Los Franceses",
        "Divino Maestro",
        "Gil Gayarre",
        "Gerardo Diego",
        "San Jose Obrero",
        "Instituto Veritas",
        "Escuelas Pias De San Fernando",
        "Everest",
        "Liceo Sorolla C",
        "Enrique De Mesa",
        "Las Cigüeñas",
        "Nuestra Señora De Navahonda",
        "San Jose",
        "Fundacion Colegio Berriz",
        "Cristo Rey",
        "Institucion Educativa Logos",
        "Santa Maria De Las Rozas",
        "Virgen De Navalazarza",
        "Vega Del Jarama",
        "Villar Palasi",
        "Ciudades Unidas",
        "Colegio-Escolania Santo Domingo De Silos",
        "San Lorenzo",
        "La Inmaculada Concepcion",
        "Real Colegio Alfonso Xii",
        "General Izquierdo",
        "San Marcos",
        "Virgen De La Nueva",
        "Francisco Carrillo",
        "Mi Cole",
        "Nuestra Señora De Valvanera",
        "Silvio Abad",
        "Joan Miro",
        "Colegio Internacional Sek-Ciudalcampo",
        "Duque De Rivas",
        "Virgen Del Rosario",
        "El Pilar",
        "Carlos Ruiz",
        "Virgen Del Rosario",
        "El Buen Gobernador",
        "Gabriel Y Galan",
        "San Juan Bosco",
        "Alba",
        "Miguel De Cervantes",
        "La Gaviota",
        "San Juan Evangelista",
        "J.A.B.Y.",
        "Isaac Peral",
        "Las Veredillas",
        "San Jose",
        "Nuestra Señora Del Pilar",
        "Alto Jarama",
        "Cardenal Cisneros",
        "San Ignacio De Loyola",
        "Los Angeles",
        "Nuestra Señora De Lourdes",
        "Nuestra Señora Del Rosario",
        "Angel Castro",
        "Juan Falco",
        "Cristo De La Salud",
        "Arzobispo Morcillo",
        "San Jose",
        "Marques De Vallejo",
        "Vicente Aleixandre",
        "Samer Calasanz",
        "Ramon Linacero",
        "Jesus Aramburu",
        "Miguel De Cervantes",
        "Valdemera",
        "Concepcion Garcia Robles",
        "Nuestra Señora De La Poveda",
        "Gregorio Canella",
        "San Damaso",
        "Santiago Apostol",
        "Colegio Internacional Sek-El Castillo",
        "San Lucas",
        "Nuestra Señora De La Victoria",
        "Santa Elena",
        "Nuestra Señora De La Victoria De Lepanto",
        "Hermanos Garcia Noblejas",
        "Colegio Alcala",
        "San Jose De Valderas",
        "San Andres",
        "Felipe Ii",
        "Ciudad De Getafe",
        "Inglan",
        "Instituto Radio Television Española (Instituto Rtve)",
        "Projardin Retiro",
        "Los Castillos",
        "Ramon Maria Del Valle Inclan",
        "Nuestra Señora De La Fuencisla",
        "Ignacio Zuloaga",
        "Virgen Del Cerro",
        "Fontarron",
        "Vicente Aleixandre",
        "Principe Felipe",
        "Ramon Perez De Ayala",
        "Los Castillos",
        "Dos Parques",
        "Cuna De Jesus",
        "Joyfe",
        "Tirso De Molina",
        "Los Angeles",
        "Amanecer",
        "Santo Domingo",
        "Cervantes",
        "Juan Gris",
        "Giner De Los Rios",
        "Severo Ochoa",
        "Vicente Aleixandre",
        "Kensington School (Britanico)",
        "Gabriel Y Galan",
        "Universidad Politecnica De Madrid",
        "Universidad Autonoma De Madrid",
        "Universidad Complutense De Madrid",
        "Universidad De Alcala De Henares",
        "San Juan Garcia",
        "Maria Inmaculada",
        "Vicente Ferrer",
        "Jesus Varela",
        "Daniel Vazquez Diaz",
        "Pardo Bazan",
        "Perez Galdos",
        "Pio Baroja",
        "El Olivar",
        "Ramon Y Cajal",
        "San Alonso De Orozco",
        "Arquitecto Pedro Gumiel",
        "Parque De Lisboa",
        "Torres Quevedo",
        "Maria Moliner",
        "Andres Manjon",
        "Dionisio Aguado",
        "Doctor Severo Ochoa",
        "Butarque",
        "Pasamonte",
        "Avenida De Los Toreros",
        "Mariano Jose De Larra",
        "La Estrella",
        "San Juan Bautista",
        "Jaime Vera",
        "Pipo's",
        "Adela Abrines Castaños",
        "Ciudad De Parla",
        "Rosalia De Castro",
        "Rio Bidasoa",
        "Manuel De Falla",
        "Las Rozas I",
        "Nuestra Señora De La Esperanza",
        "Gonzalo Torrente Ballester",
        "Andal Alameda",
        "Nuestra Señora De Loreto",
        "Ramiro De Maeztu",
        "Juan De Herrera",
        "Beatriz Galindo",
        "Dulcinea",
        "Juan De Austria",
        "Santos Niños",
        "Emilio Casado",
        "Santiago Ramon Y Cajal",
        "Vicente Aleixandre",
        "Francisco De Quevedo",
        "Lope De Vega",
        "Dionisio Ridruejo",
        "Las Cumbres",
        "Juan Ramon Jimenez",
        "Andal",
        "Principe De Asturias",
        "Meseta De Orcasitas",
        "Luis Feito",
        "San Miguel",
        "Palomeras Bajas",
        "Vallecas",
        "Seminario Arzobispal La Inmaculada Y San Damaso",
        "Arcangel Rafael",
        "Salzillo-Valle Inclan",
        "King's College",
        "Sagrado Corazon Reparadoras",
        "San Fernando",
        "Santa Teresa De Jesus",
        "Miguel Hernandez",
        "Francisco De Quevedo",
        "Inmaculada Concepcion",
        "Miguel De Cervantes",
        "Leo Kanner",
        "Los Peñascales",
        "Colegio Escandinavo (Sueco)",
        "Hof Der Lage Landen (Paises Bajos)",
        "Numont School (Britanico)",
        "Ecole Saint-Exupery (Frances)",
        "Lycee Moliere (Frances)",
        "Gonzalo De Berceo",
        "Menendez Pidal",
        "Buenos Aires",
        "American School Of Madrid (Ee.Uu.)",
        "The English Montessori School (Britanico)",
        "International School Of Madrid (Britan.)",
        "Parque",
        "Casa De La Cultura",
        "Cultural Moratalaz",
        "Aluche",
        "Fortuny",
        "Ciudad De Los Poetas",
        "Ramon Y Cajal",
        "Miguel Delibes",
        "Celestino Mutis",
        "Damaso Alonso",
        "Cardenal Herrera Oria",
        "Agustina De Aragon",
        "Humanejos",
        "Leon Felipe",
        "Scuola Statale Italiana De Madrid (Italiano)",
        "Prado De Santo Domingo",
        "Nuestra Señora De Moratalaz",
        "Nazaret",
        "Manuel Azaña",
        "Iplacea",
        "Mariano Benlliure",
        "Antonio Machado",
        "Federico Garcia Lorca",
        "Pradolongo",
        "Vicalvaro",
        "San Sebastian",
        "Ciudad Del Aire",
        "San Juan Bautista",
        "Arturo Soria",
        "San Miguel Ii",
        "La Purisima",
        "Fomento-Fundacion",
        "K.S.",
        "Valdepalitos",
        "Federico Garcia Lorca",
        "Federico Garcia Lorca",
        "Mateo Aleman",
        "Galileo Galilei",
        "Blas De Otero",
        "San Mateo",
        "Mariana Pineda",
        "Vallecas-Magerit",
        "Las Musas",
        "Barrio De Bilbao",
        "Leonardo Da Vinci",
        "Moratalaz",
        "Miguel Hernandez",
        "Luis De Gongora",
        "Gerardo Diego",
        "Miguel Servet",
        "Breogan",
        "Virgen Del Cortijo",
        "Ciudad De Roma",
        "La Latina",
        "Blas De Otero",
        "Pinar Prados De Torrejon",
        "Leon Felipe",
        "Fuentesanta",
        "Aula 3",
        "Mariano Jose De Larra",
        "Pablo Picasso",
        "Arlequin",
        "Celso Emilio Ferreiro",
        "Francisco De Quevedo",
        "Jose Maria De Pereda",
        "Julian Besteiro",
        "Antonio Machado",
        "Felipe Iv",
        "Antonio Machado",
        "Antonio Machado",
        "Escuela Superior De Hosteleria Y Turismo",
        "Centro De Formacion Tecnica",
    ];

    /**
     * A random School Name.
     * @return string
     */
    public function schoolName()
    {
        return static::randomElement(static::$schoolNames);
    }
}